name: C++ CI Build

on:
  push:
    branches:
      - main  # 触发工作流的分支
  pull_request:
    branches:
      - main  # 触发PR时的工作流分支

jobs:
  build:
    runs-on: ubuntu-latest  # 你可以选择适合你的操作系统，如ubuntu-latest, windows-latest等

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: cmake/setup-cmake@v3  # 使用 cmake/setup-cmake

    - name: Install build tools
      run: |
        sudo apt update
        sudo apt install -y build-essential  # 安装编译工具（gcc, g++等）

    - name: Configure CMake project
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../  # 你可以根据需要调整构建类型

    - name: Build the project
      run: |
        cd build
        cmake --build . --config Release  # 指定构建配置，可以根据需要调整

    - name: Run tests (optional)
      run: |
        cd build
        cmake --build . --target test  # 如果你的项目有测试，可以启用此步骤

    - name: Upload build artifacts (optional)
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build  # 将构建目录上传为构建产物（如果需要）
